language: python
python:
  - 3.5
install:
  - pip install sphinx sphinx_rtd_theme
script: make html
script: ls -la build/html

deploy:
    - provider: pages
      skip_cleanup: true
      local_dir: build/html/  # or remove this line to upload from root of repo
      github_token: $GITHUB_TOKEN  
      on:
        branch: master
  